version: "3.8"

services:
  app:
    build:
      context: .
    container_name: backend-test-app
    restart: always
    image: agusheryanto182/backend-test-app:latest
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /app/dist
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: ${PORT}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      PRODUCTION: ${PRODUCTION}
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend_test_db_2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
