name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code dari GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Menambahkan file .env menggunakan GitHub Secrets
      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "LOGGER_LEVEL=${{ secrets.LOGGER_LEVEL }}" >> .env
          echo "PRODUCTION=${{ secrets.PRODUCTION }}" >> .env

      # 3. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Install dependencies dan setup Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      # 6. Build Docker image menggunakan Makefile
      - name: Build Docker image
        run: make build

      # 7. Jalankan Docker container (dalam mode detached)
      - name: Run Docker containers
        run: make up

      # 8. Push Docker image ke Docker Hub
      - name: Push Docker image to Docker Hub
        run: make push

      # 9. Clean up docker containers and volumes
      - name: Clean up
        run: make clean

      # 10. Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/repositories/backend-task-2
            git pull origin master
            docker compose down  
            docker compose up -d
