name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: backend_test_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Checkout code dari GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup Docker untuk Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Install dependencies dan setup Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      # 5. Build Docker image menggunakan Makefile
      - name: Build Docker image
        run: make build

      # 6. Jalankan Docker container (dalam mode detached)
      - name: Run Docker containers
        run: make up

      # 7. Push Docker image ke Docker Hub
      - name: Push Docker image to Docker Hub
        run: make push

      # 8. Clean up docker containers and volumes
      - name: Clean up
        run: make clean

      # 9. Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/repositories/backend-task-2
            git pull origin master
            docker-compose down  
            docker-compose up -d